# Site settings
title: "About Me"
description: "I am a software engineer with interests in DevOps, Site Reliability, and System Administration.  I am happiest when tinkering with something new and exciting!"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jordan Murray"
resume_title:                   "Software Engineer"
resume_contact_email:
  "djm@murrayfoundry.com"
resume_header_contact_info: "Winston-Salem, NC | djm@murrayfoundry.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/FueledbyJordan"
  #resume_twitter_url:           "link"
  #resume_dribbble_url:          "link"
  #resume_facebook_url:          "https://www.facebook.com/FueledbyJordan"
  resume_linkedin_url:          "https://www.linkedin.com/in/fueledbyjordan/"
  # resume_instagram_url:         "link"
  #resume_website_url:           "link"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
